version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    volumes:
      - ./frontend:/app/frontend
    restart: always
    ports:
      - "5173:5173"

  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    volumes:
      - ./backend:/app/backend
    restart: always
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgres://postgres:1234@postgres:5432/usertodo?sslmode=disable
    ports:
      - "5174:5174"

  postgres:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: usertodo
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"

  migrate:
    image: migrate/migrate
    depends_on:
      - postgres
    volumes:
      - ./backend/pkg/db/migrations:/migrations
    command: [ "-path", "/migrations", "-database", "postgres://postgres:1234@postgres:5432/usertodo?sslmode=disable", "up"]

volumes:
  postgres_data:
